export const LOADED_FAVS = 'LOADED_FAVS';
export const LOADED_COLLECTIONS = 'LOADED_COLLECTIONS';
export const LOADED_CITIES = 'LOADED_CITIES';
export const LOADED_RESTAURANTS = 'LOADED_RESTAURANTS';
export const LOADED_CATEGORIES = 'LOADED_CATEGORIES';
export const LOADED_LOCATION = 'LOADED_LOCATION';
export const LOADED_LOCATION_DETAILS = 'LOADED_LOCATION_DETAILS';
export const ADD_USER = 'ADD_USER';
export const VALID_LOGIN = 'VALID_LOGIN';
export const VALID_LOGOUT = 'VALID_LOGOUT';

